apiVersion: v1
entries:
  mynginx:
  - apiVersion: v1
    appVersion: "1"
    created: "2022-02-17T05:50:37.1505418-08:00"
    description: Helm Chart tp deploy nginx
    digest: c7b548bb3f8f76b1f9ec94c872bf75f68149e57f8da2fd39b340118937a6f966
    name: mynginx
    urls:
    - mynginx-0.1.0.tgz
    version: 0.1.0
generated: "2022-02-17T05:50:37.1499973-08:00"
